-- phpMyAdmin SQL Dump
-- version 4.7.0
-- https://www.phpmyadmin.net/
--
-- Hôte : 127.0.0.1:3307
-- Généré le :  ven. 24 nov. 2017 à 21:50
-- Version du serveur :  10.1.25-MariaDB
-- Version de PHP :  7.1.7

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données :  `actus`
--

-- --------------------------------------------------------

--
-- Structure de la table `actus`
--

CREATE TABLE `actus` (
  `id` int(11) NOT NULL,
  `banner-url` varchar(1024) NOT NULL,
  `upper_title` varchar(40) NOT NULL,
  `title` varchar(60) NOT NULL,
  `header_url` varchar(1024) NOT NULL,
  `date` date NOT NULL,
  `image_url` varchar(1024) NOT NULL,
  `ressource_url` varchar(1024) NOT NULL,
  `content` varchar(12000) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Déchargement des données de la table `actus`
--

INSERT INTO `actus` (`id`, `banner-url`, `upper_title`, `title`, `header_url`, `date`, `image_url`, `ressource_url`, `content`) VALUES
(1, 'http://192.168.137.1:8080/actusplus/files/bandeau.jpg', 'celebrities News', '11 celebrities who have aged beautifully', 'http://192.168.137.1:8080/actusplus/files/header.png', '2017-08-30', 'http://192.168.137.1:8080/actusplus/files/thambnail.png', 'http://192.168.137.1:8080/actusplus/files/Clip_1080_5sec_10mbps_h264.mp4', '11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully'),
(2, 'http://192.168.137.1:8080/actusplus/files/bandeau.jpg', 'War News', '5 lies that ends with War', 'http://192.168.137.1:8080/actusplus/files/header.png', '2017-08-30', 'http://192.168.137.1:8080/actusplus/files/youtubephoto.png', 'http://192.168.137.1:8080/actusplus/files/Clip_1080_5sec_10mbps_h264.mp4', '5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War'),
(3, 'http://192.168.137.1:8080/actusplus/files/bandeau.jpg', 'celebrities News', '11 celebrities who have aged beautifully', 'http://192.168.137.1:8080/actusplus/files/header.png', '2017-08-30', 'http://192.168.137.1:8080/actusplus/files/thambnail.png', 'http://192.168.137.1:8080/actusplus/files/Clip_1080_5sec_10mbps_h264.mp4', '11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully'),
(4, 'http://192.168.137.1:8080/actusplus/files/bandeau.jpg', 'War News', '5 lies that ends with War', 'http://192.168.137.1:8080/actusplus/files/header.png', '2017-08-30', 'http://192.168.137.1:8080/actusplus/files/youtubephoto.png', 'http://192.168.137.1:8080/actusplus/files/Clip_1080_5sec_10mbps_h264.mp4', '5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War'),
(5, 'http://192.168.137.1:8080/actusplus/files/bandeau.jpg', 'celebrities News', '11 celebrities who have aged beautifully', 'http://192.168.137.1:8080/actusplus/files/header.png', '2017-08-30', 'http://192.168.137.1:8080/actusplus/files/thambnail.png', 'http://192.168.137.1:8080/actusplus/files/Clip_1080_5sec_10mbps_h264.mp4', '11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully'),
(6, 'http://192.168.137.1:8080/actusplus/files/bandeau.jpg', 'War News', '5 lies that ends with War', 'http://192.168.137.1:8080/actusplus/files/header.png', '2017-08-30', 'http://192.168.137.1:8080/actusplus/files/youtubephoto.png', 'http://192.168.137.1:8080/actusplus/files/Clip_1080_5sec_10mbps_h264.mp4', '5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War'),
(7, 'http://192.168.137.1:8080/actusplus/files/bandeau.jpg', 'celebrities News', '11 celebrities who have aged beautifully', 'http://192.168.137.1:8080/actusplus/files/header.png', '2017-08-30', 'http://192.168.137.1:8080/actusplus/files/thambnail.png', 'http://192.168.137.1:8080/actusplus/files/Clip_1080_5sec_10mbps_h264.mp4', '11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully'),
(8, 'http://192.168.137.1:8080/actusplus/files/bandeau.jpg', 'War News', '5 lies that ends with War', 'http://192.168.137.1:8080/actusplus/files/header.png', '2017-08-30', 'http://192.168.137.1:8080/actusplus/files/youtubephoto.png', 'http://192.168.137.1:8080/actusplus/files/Clip_1080_5sec_10mbps_h264.mp4', '5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War'),
(9, 'http://192.168.137.1:8080/actusplus/files/bandeau.jpg', 'celebrities News', '11 celebrities who have aged beautifully', 'http://192.168.137.1:8080/actusplus/files/header.png', '2017-08-30', 'http://192.168.137.1:8080/actusplus/files/thambnail.png', 'http://192.168.137.1:8080/actusplus/files/Clip_1080_5sec_10mbps_h264.mp4', '11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully'),
(10, 'http://192.168.137.1:8080/actusplus/files/bandeau.jpg', 'War News', '5 lies that ends with War', 'http://192.168.137.1:8080/actusplus/files/header.png', '2017-08-30', 'http://192.168.137.1:8080/actusplus/files/youtubephoto.png', 'http://192.168.137.1:8080/actusplus/files/Clip_1080_5sec_10mbps_h264.mp4', '5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War'),
(11, 'http://192.168.137.1:8080/actusplus/files/bandeau.jpg', 'celebrities News', '11 celebrities who have aged beautifully', 'http://192.168.137.1:8080/actusplus/files/header.png', '2017-08-30', 'http://192.168.137.1:8080/actusplus/files/thambnail.png', 'http://192.168.137.1:8080/actusplus/files/Clip_1080_5sec_10mbps_h264.mp4', '11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully'),
(12, 'http://192.168.137.1:8080/actusplus/files/bandeau.jpg', 'War News', '5 lies that ends with War', 'http://192.168.137.1:8080/actusplus/files/header.png', '2017-08-30', 'http://192.168.137.1:8080/actusplus/files/youtubephoto.png', 'http://192.168.137.1:8080/actusplus/files/Clip_1080_5sec_10mbps_h264.mp4', '5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War'),
(13, 'http://192.168.137.1:8080/actusplus/files/bandeau.jpg', 'celebrities News', '11 celebrities who have aged beautifully', 'http://192.168.137.1:8080/actusplus/files/header.png', '2017-08-30', 'http://192.168.137.1:8080/actusplus/files/thambnail.png', 'http://192.168.137.1:8080/actusplus/files/Clip_1080_5sec_10mbps_h264.mp4', '11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully'),
(14, 'http://192.168.137.1:8080/actusplus/files/bandeau.jpg', 'War News', '5 lies that ends with War', 'http://192.168.137.1:8080/actusplus/files/header.png', '2017-08-30', 'http://192.168.137.1:8080/actusplus/files/youtubephoto.png', 'http://192.168.137.1:8080/actusplus/files/Clip_1080_5sec_10mbps_h264.mp4', '5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War'),
(15, 'http://192.168.137.1:8080/actusplus/files/bandeau.jpg', 'celebrities News', '11 celebrities who have aged beautifully', 'http://192.168.137.1:8080/actusplus/files/header.png', '2017-08-30', 'http://192.168.137.1:8080/actusplus/files/thambnail.png', 'http://192.168.137.1:8080/actusplus/files/Clip_1080_5sec_10mbps_h264.mp4', '11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully'),
(16, 'http://192.168.137.1:8080/actusplus/files/bandeau.jpg', 'War News', '5 lies that ends with War', 'http://192.168.137.1:8080/actusplus/files/header.png', '2017-08-30', 'http://192.168.137.1:8080/actusplus/files/youtubephoto.png', 'http://192.168.137.1:8080/actusplus/files/Clip_1080_5sec_10mbps_h264.mp4', '5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War'),
(17, 'http://192.168.137.1:8080/actusplus/files/bandeau.jpg', 'celebrities News', '11 celebrities who have aged beautifully', 'http://192.168.137.1:8080/actusplus/files/header.png', '2017-08-30', 'http://192.168.137.1:8080/actusplus/files/thambnail.png', 'http://192.168.137.1:8080/actusplus/files/Clip_1080_5sec_10mbps_h264.mp4', '11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully'),
(18, 'http://192.168.137.1:8080/actusplus/files/bandeau.jpg', 'War News', '5 lies that ends with War', 'http://192.168.137.1:8080/actusplus/files/header.png', '2017-08-30', 'http://192.168.137.1:8080/actusplus/files/youtubephoto.png', 'http://192.168.137.1:8080/actusplus/files/Clip_1080_5sec_10mbps_h264.mp4', '5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War'),
(19, 'http://192.168.137.1:8080/actusplus/files/bandeau.jpg', 'celebrities News', '11 celebrities who have aged beautifully', 'http://192.168.137.1:8080/actusplus/files/header.png', '2017-08-30', 'http://192.168.137.1:8080/actusplus/files/thambnail.png', 'http://192.168.137.1:8080/actusplus/files/Clip_1080_5sec_10mbps_h264.mp4', '11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully'),
(20, 'http://192.168.137.1:8080/actusplus/files/bandeau.jpg', 'War News', '5 lies that ends with War', 'http://192.168.137.1:8080/actusplus/files/header.png', '2017-08-30', 'http://192.168.137.1:8080/actusplus/files/youtubephoto.png', 'http://192.168.137.1:8080/actusplus/files/Clip_1080_5sec_10mbps_h264.mp4', '5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War'),
(21, 'http://192.168.137.1:8080/actusplus/files/bandeau.jpg', 'celebrities News', '11 celebrities who have aged beautifully', 'http://192.168.137.1:8080/actusplus/files/header.png', '2017-08-30', 'http://192.168.137.1:8080/actusplus/files/thambnail.png', 'http://192.168.137.1:8080/actusplus/files/Clip_1080_5sec_10mbps_h264.mp4', '11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully'),
(22, 'http://192.168.137.1:8080/actusplus/files/bandeau.jpg', 'War News', '5 lies that ends with War', 'http://192.168.137.1:8080/actusplus/files/header.png', '2017-08-30', 'http://192.168.137.1:8080/actusplus/files/youtubephoto.png', 'http://192.168.137.1:8080/actusplus/files/Clip_1080_5sec_10mbps_h264.mp4', '5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War'),
(23, 'http://192.168.137.1:8080/actusplus/files/bandeau.jpg', 'celebrities News', '11 celebrities who have aged beautifully', 'http://192.168.137.1:8080/actusplus/files/header.png', '2017-08-30', 'http://192.168.137.1:8080/actusplus/files/thambnail.png', 'http://192.168.137.1:8080/actusplus/files/Clip_1080_5sec_10mbps_h264.mp4', '11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully'),
(24, 'http://192.168.137.1:8080/actusplus/files/bandeau.jpg', 'War News', '5 lies that ends with War', 'http://192.168.137.1:8080/actusplus/files/header.png', '2017-08-30', 'http://192.168.137.1:8080/actusplus/files/youtubephoto.png', 'http://192.168.137.1:8080/actusplus/files/Clip_1080_5sec_10mbps_h264.mp4', '5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War'),
(25, 'http://192.168.137.1:8080/actusplus/files/bandeau.jpg', 'celebrities News', '11 celebrities who have aged beautifully', 'http://192.168.137.1:8080/actusplus/files/header.png', '2017-08-30', 'http://192.168.137.1:8080/actusplus/files/thambnail.png', 'http://192.168.137.1:8080/actusplus/files/Clip_1080_5sec_10mbps_h264.mp4', '11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully'),
(26, 'http://192.168.137.1:8080/actusplus/files/bandeau.jpg', 'War News', '5 lies that ends with War', 'http://192.168.137.1:8080/actusplus/files/header.png', '2017-08-30', 'http://192.168.137.1:8080/actusplus/files/youtubephoto.png', 'http://192.168.137.1:8080/actusplus/files/Clip_1080_5sec_10mbps_h264.mp4', '5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War'),
(27, 'http://192.168.137.1:8080/actusplus/files/bandeau.jpg', 'celebrities News', '11 celebrities who have aged beautifully', 'http://192.168.137.1:8080/actusplus/files/header.png', '2017-08-30', 'http://192.168.137.1:8080/actusplus/files/thambnail.png', 'http://192.168.137.1:8080/actusplus/files/Clip_1080_5sec_10mbps_h264.mp4', '11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully'),
(28, 'http://192.168.137.1:8080/actusplus/files/bandeau.jpg', 'War News', '5 lies that ends with War', 'http://192.168.137.1:8080/actusplus/files/header.png', '2017-08-30', 'http://192.168.137.1:8080/actusplus/files/youtubephoto.png', 'http://192.168.137.1:8080/actusplus/files/Clip_1080_5sec_10mbps_h264.mp4', '5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War'),
(29, 'http://192.168.137.1:8080/actusplus/files/bandeau.jpg', 'celebrities News', '11 celebrities who have aged beautifully', 'http://192.168.137.1:8080/actusplus/files/header.png', '2017-08-30', 'http://192.168.137.1:8080/actusplus/files/thambnail.png', 'http://192.168.137.1:8080/actusplus/files/Clip_1080_5sec_10mbps_h264.mp4', '11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully'),
(30, 'http://192.168.137.1:8080/actusplus/files/bandeau.jpg', 'War News', '5 lies that ends with War', 'http://192.168.137.1:8080/actusplus/files/header.png', '2017-08-30', 'http://192.168.137.1:8080/actusplus/files/youtubephoto.png', 'http://192.168.137.1:8080/actusplus/files/Clip_1080_5sec_10mbps_h264.mp4', '5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War'),
(31, 'http://192.168.137.1:8080/actusplus/files/bandeau.jpg', 'celebrities News', '11 celebrities who have aged beautifully', 'http://192.168.137.1:8080/actusplus/files/header.png', '2017-08-30', 'http://192.168.137.1:8080/actusplus/files/thambnail.png', 'http://192.168.137.1:8080/actusplus/files/Clip_1080_5sec_10mbps_h264.mp4', '11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully\r\n11 celebrities who have aged beautifully'),
(32, 'http://192.168.137.1:8080/actusplus/files/bandeau.jpg', 'War News', '5 lies that ends with War', 'http://192.168.137.1:8080/actusplus/files/header.png', '2017-08-30', 'http://192.168.137.1:8080/actusplus/files/youtubephoto.png', 'http://192.168.137.1:8080/actusplus/files/Clip_1080_5sec_10mbps_h264.mp4', '5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War5 lies that ends with War');

-- --------------------------------------------------------

--
-- Structure de la table `compte`
--

CREATE TABLE `compte` (
  `login` varchar(40) NOT NULL,
  `password` varchar(45) NOT NULL,
  `nom` varchar(20) NOT NULL,
  `prenom` varchar(20) NOT NULL,
  `gender` varchar(10) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Déchargement des données de la table `compte`
--

INSERT INTO `compte` (`login`, `password`, `nom`, `prenom`, `gender`) VALUES
('chakib.daii@gmail.com', 'lZ2Xa5g=', 'sdfsdf', 'Chakib', 'male'),
('chakib@gmail.com', 'lZ2Xa5g=', 'chakib', 'daii', 'Male');

-- --------------------------------------------------------

--
-- Structure de la table `favoris`
--

CREATE TABLE `favoris` (
  `login` varchar(40) NOT NULL,
  `id_actus` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Déchargement des données de la table `favoris`
--

INSERT INTO `favoris` (`login`, `id_actus`) VALUES
('chakib@gmail.com', 3),
('chakib@gmail.com', 9),
('chakib@gmail.com', 31),
('chakib@gmail.com', 32);

--
-- Index pour les tables déchargées
--

--
-- Index pour la table `actus`
--
ALTER TABLE `actus`
  ADD PRIMARY KEY (`id`);

--
-- Index pour la table `compte`
--
ALTER TABLE `compte`
  ADD PRIMARY KEY (`login`);

--
-- Index pour la table `favoris`
--
ALTER TABLE `favoris`
  ADD PRIMARY KEY (`login`,`id_actus`),
  ADD KEY `id_actus_idx` (`id_actus`);

--
-- AUTO_INCREMENT pour les tables déchargées
--

--
-- AUTO_INCREMENT pour la table `actus`
--
ALTER TABLE `actus`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=33;
--
-- Contraintes pour les tables déchargées
--

--
-- Contraintes pour la table `favoris`
--
ALTER TABLE `favoris`
  ADD CONSTRAINT `id_actus` FOREIGN KEY (`id_actus`) REFERENCES `actus` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `login` FOREIGN KEY (`login`) REFERENCES `compte` (`login`) ON DELETE CASCADE ON UPDATE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
